### ISSUE TITLE
Versioning scheme

### ISSUE THREAD

**Issue by dvershinin** [xcir/libvmod-xcounter#1]
The current versioning scheme seems a bit out of line (compared to other VMODs).

For example, last release v61.2 works just fine with Varnish 6.0, not only with Varnish 6.1.

So I think it is better to stick to simple versioning like 1.0.0 that does not depend on Varnish version. The Varnish compatibility info in the README.md file is enough.

Thanks for your great work :)

**Comment by xcir** [comment]
Hi, dvershinin. Thanks comment.

As you said, v61.1 supports 6.0.x and 6.1.x.
But, x.y.z versioning scheme is confuse to think about keeping updating in multiple Varnish version, if incompatible version comes out in the future.

ex)
1.0.1 = initial release for 6.0.x/6.1.x
1.0.2 = initial release for 7.0.x
1.0.3 = new feature for 6.0.x/6.1.x
1.0.4 = new feature for 7.0.x
...

I think current versioning scheme NOT BEST but better.
