### ISSUE TITLE
Memory leak in vmod_vsc__init

### ISSUE THREAD

**Issue by stevendore** [xcir/libvmod-xcounter#16]
When `hidecold` is false `ds` is lost track of. This was spotted by clang's scan-build with `scan-build make`.

https://github.com/xcir/libvmod-xcounter/blob/8aebc77ce8c2b26bb0b610690185c0df3ba270ca/src/vmod_xcounter.c#L225-L232

**Comment by xcir** [comment]
Thanks for the report.
The bug has been identified and fixed in my local, but I will be away on a trip for a few days starting tomorrow, so the push will be done over the weekend.

**Comment by xcir** [comment]
Fixed, Thanks!
